.\"     Title: dbmail\-users
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 07/28/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "DBMAIL\-USERS" "8" "07/28/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
dbmail\-users \- manages the DBMail user database.
.SH "SYNOPSIS"
dbmail\-users { \-a username | \-c username } [ \-g clientid ] [ \-m maxmail] [ \-p passwordtype ] [ \-P shadowfile ] [ \-w password ] [ \-W passwordfile] [ \-u username ] [ \-s aliases ] [ \-S aliases ]
.sp
dbmail\-users { \-d username | \-e username }
.sp
dbmail\-users \-l userspec
.sp
dbmail\-users \-x alias [ \-t forwards ] [ \-T forwards ]
.SH "DESCRIPTION"
The dbmail\-users program enables you to manage the DBMail users. It lets you add, delete and change users as well as show information about a specific user or display a list of existing users. It also has the capability of adding/removing separate aliases.
.SH "MODE OPTIONS"
.TP 3n
\-a user
Add a user
.TP 3n
\-d user
Delete a user
.TP 3n
\-c user
Change details for a user
.TP 3n
\-e user
Empty all mailboxes for a user
.TP 3n
\-l uspec
List information for matching users
.TP 3n
\-x alias
Create an external forwarding address
.SH "MINOR OPTIONS"
.TP 3n
\-w passwd
Specify user's password on the command line
.TP 3n
\-W [file]
Read from a file or prompt for a user's password
.TP 3n
\-p pwtype
Password type may be one of the following: plaintext, crypt, md5\-hash, md5\-digest, crypt\-raw, md5\-hash\-raw, md5\-digest\-raw, md5\-base64, md5\-base64\-raw.
.TP 3n
\-P [file]
Pull encrypted password from the shadow file
.TP 3n
\-u user
New username (only useful for \-c, change)
.TP 3n
\-g cid
Assign the user to a client group.
.TP 3n
\-m max
Set the maximum mail quota in <bytes>B, <kbytes>K, or <mbytes>M, default in bytes If set to 0, there will be no limit.
.TP 3n
\-s alias[,alias\&...]
Adds a list of recipient aliases. An alias is an e\-mail address that is being delivered to the DBMail mailsystem and should be delivered to this user.
.TP 3n
\-S alias[,alias\&...]
Removes a list of recipient aliases. Use wildcards ? and * to match any single character and any number of characters, respectively.
.TP 3n
\-t forward[,forward\&...]
Adds a list of deliver\-to forwards.
.TP 3n
\-T forward[,forward\&...]
Removes a list of deliver\-to forwards. Use wildcards ? and * to match any single character and any number of characters, respectively.
.SH "COMMON OPTIONS"
.TP 3n
\-f configfile
Specify an alternate config file. The utilities are currently hardcoded to use /etc/dbmail.conf for their configs, and will halt if the config file cannot be found. Use the \-f configfile option to specify your system's preferred config file location.
.TP 3n
\-q
Quietly skip interactive prompts and helpful status messages which would otherwise be printed to stdout. Use two \-q's to silence errors which would otherwise be printed to stderr.
.TP 3n
\-v
Operate verbosely. Some of the utilities in the DBMail suite can take two \-v's for extra verbosity. Those which don't understand this convention won't complain about having the extra \-v and will simply operate at their normal verbosity.
.TP 3n
\-V
Show the version and copyright, then exit.
.TP 3n
\-h
Show a brief summary of options, then exit.
.SH "ALIASES VS. FORWARDS"
One question we often see on the dbmail@dbmail.org mailing list is what the difference is between aliases and forwards. When using dbmail\-users, the different command line options are there because an alias attaches some arbitrary address to a particular user's account, while a forward attaches some arbitrary address another arbitrary address or pipe out.
.sp
When using dbmail\-users with major option \-c, you must use minor option \-s/\-S for modifying aliases. When using dbmail\-users with major option \-x, you must use \-t/\-T for modifying forwards.
.SH "ALIASES"
When creating a new user account, you must either add an initial alias that delivers to the account name, or make the account in the form of a fully qualified email address. For example, the user named \fIBaz\fR created like this:
.sp
.RS 3n
.nf
dbmail\-users \-a baz \-p crypt \-w psword
.fi
.sp
.RE
will \fBnot\fR actually receive any mail yet! You must be sure to add an alias:
.sp
.RS 3n
.nf
dbmail\-users \-c baz \-s baz@foodomain
.fi
.sp
.RE
You may add multiple aliases by repeatedly calling the dbmail\-users(8) utility, or by calling it with a comma\-separated list of aliases:
.sp
.RS 3n
.nf
dbmail\-users \-c baz \-s baz@foodomain,baz@bardomain
.fi
.sp
.RE
Three catch\-all modes are also supported, for domains, sub\-domains, and local parts:
.sp
.RS 3n
.nf
dbmail\-users \-a baz \-s @bazdomain
.fi
.RE
.sp
.RS 3n
.nf
dbmail\-users \-a baz \-s @.allsubs.bazdomain
.fi
.RE
.sp
.RS 3n
.nf
dbmail\-users \-a baz \-s baz@
.fi
.sp
.RE
The first example catches email addressed to any user @bazdomain and delivers it to Baz's INBOX. The second example catch email address to any user at any subdomain below .allsubs.bazdomain (\fBnot\fR including allsubs.bazdomain itself!) The third example catches email addressed to baz@ at any domain.
.sp
There is no support for delivering to a particular mailbox other than INBOX via the aliases system. Please use a Sieve script to sort mail like this.
.SH "FORWARDS"
Incoming messages addressed to particular email addresses can be forwarded out to outside email addresses, piped out to a command (when prepended with | \fIpipe\fR) or piped out with an mbox\-style From line to a command (when prepended with ! \fIbang\fR). For example:
.sp
.RS 3n
.nf
dbmail\-users \-x bar@domain \-t bar@another.domain
.fi
.RE
.sp
.RS 3n
.nf
dbmail\-users \-x bar@domain \-t "|/usr/sbin/superspamtrapper"
.fi
.RE
.sp
.RS 3n
.nf
dbmail\-users \-x bar@domain \-t "!cat > /var/spool/mail/bar/whatever.mbox"
.fi
.sp
.RE
Forwards can be listed using the same \-l command as for users. For example, to see where the local address bar@domain might be forwarded to, use this:
.sp
.RS 3n
.nf
dbmail\-users \-l bar@domain
  forward [bar@domain] to [bar@another.domain]
  forward [bar@domain] to [|/usr/sbin/superspamtrapper]
  forward [bar@domain] to [!cat > /var/spool/mail/bar/whatever.mbox]
.fi
.sp
.RE
Forwards can be removed using basic glob style pattern matching. A ? \fIquestion\fR means "match zero or one of any character" and * \fIasterisk\fR means "match zero or more of any character." For example:
.sp
.RS 3n
.nf
dbmail\-users \-x bar@domain \-T "*"
.fi
.sp
.RE
will complete and totally remove the \fIbar@domain\fR external alias and all of its forwarding addresses and commands.
.SH "BUGS"
If you experience inexplicable problems with DBMail, please report the issue to the [1]\&\fIDBMail Bug Tracker\fR.
.SH "LICENSE"
DBMail and its components are distributed under the terms of the GNU General Public License. Copyrights are held variously by the authors listed below.
.SH "AUTHOR(S)"
DBMail is a collaborative effort among the core developers listed below and the tremendous help of the testers, patchers and bug hunters listed in the AUTHORS and THANKS files found in the DBMail source distribution.
.sp
.RS 3n
.nf
Eelco van Beek      Aaron Stone            Paul J Stevens
Roel Rozendaal      Open Source Engineer   NFG Net Facilities Group BV
Ilja Booij          Palo Alto, CA USA      http://www.nfg.nl
IC&S                http://hydricacid.com
Koningsweg 4
3582 GE Utrecht
http://www.ic\-s.nl
.fi
.sp
.RE
.SH "REFERENCES"
.TP 3
1.\ DBMail Bug Tracker
\%http://dbmail.org/index.php?page=bugs
