.\"     Title: dbmail
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 07/28/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "DBMAIL" "1" "07/28/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
dbmail \- the Database Mailer, is a suite of mail storage and retrieval programs centered around a database backend.
.SH "SYNOPSIS"
See one of the following man pages for more information about the components of a DBMail system:
.sp
.RS 3n
.nf
Configuration file . . . . dbmail.conf(5)
Deliver mail . . . . . . . dbmail\-smtp(1)
Manage user accounts . . . dbmail\-users(8)
Export mailbox contents. . dbmail\-export(8)
Manage Sieve scripts . . . dbmail\-sievecmd(8)
Maintain health. . . . . . dbmail\-util(8)
IMAP daemon. . . . . . . . dbmail\-imapd(8)
POP3 daemon. . . . . . . . dbmail\-pop3d(8)
LMTP daemon. . . . . . . . dbmail\-lmtpd(8)
ManageSieve daemon . . . . dbmail\-timsieved(8)
.fi
.sp
.RE
.SH "BUGS"
If you experience inexplicable problems with DBMail, please report the issue to the [1]\&\fIDBMail Bug Tracker\fR.
.SH "LICENSE"
DBMail and its components are distributed under the terms of the GNU General Public License. Copyrights are held variously by the authors listed below.
.SH "AUTHOR(S)"
DBMail is a collaborative effort among the core developers listed below and the tremendous help of the testers, patchers and bug hunters listed in the AUTHORS and THANKS files found in the DBMail source distribution.
.sp
.RS 3n
.nf
Eelco van Beek      Aaron Stone            Paul J Stevens
Roel Rozendaal      Open Source Engineer   NFG Net Facilities Group BV
Ilja Booij          Palo Alto, CA USA      http://www.nfg.nl
IC&S                http://hydricacid.com
Koningsweg 4
3582 GE Utrecht
http://www.ic\-s.nl
.fi
.sp
.RE
.SH "REFERENCES"
.TP 3
1.\ DBMail Bug Tracker
\%http://dbmail.org/index.php?page=bugs
