.TH DBMAIL-SMTP 1 
.ad
.fi
.SH NAME
dbmail-smtp
\-
Inserts messages into the 
.B DDmail
mailsystem

.SH SYNOPSIS
.B dbmail-smtp
[\fB-n\fR \fIheaderfield\fR] [\fB-d\fR \fIaddresses\fR] [\fB-u \fIusernames\fR] [\fB-m\fR \fImailboxname\fR] [\fB-r\fR \fIreturn path\fR] [\fB-f\fR \fIfile\fR]
.SH DESCRIPTION
.ad
.fi
The 
.B dbmail-smtp 
program inserts messages from the commandline or from any MTA into the 
.B DBmail
mailsystem. The program reads from standard input.

.SH OPTIONS

.IP "-n headerfield" 
Deliver messages to the recipient MIME header specified in 
.I headerfield. 
The default header to use is the "Deliver-To:" header.
.IP "-d addresses"
Deliver messages to the recipients specified by 
.I addresses.
This option is mostly used for delivery to \fBDBmail\fR from an MTA. It is possible to set multiple recipient addresses by setting several
.B -d 
options.
.IP "-u usernames"
Deliver messages straight to a users with username 
.I usernames.
It is possible to set multiple recipients by setting several
.B -u
options.
.IP "-m mailboxname"
Deliver messages to mailbox \fImailboxname\fR of the recipient. If this mailbox does not exist yet, it is created.
.IP "-r return path"
Set return path for bounces and other error reports to 
.I return path.
.IP "-f file"
Use config file 
.I file
instead of the default config file.
.SH DIAGNOSTICS
.ad
.fi
Errors and notifications are send to the trace output as set 
in the \fBDbmail\fR configfile.

.SH BUGS
.PP
There are no known bugs. Work is being done on effiency and speed improvement.
.SH LICENSE
.na
.nf
.ad
.fi
Dbmail and it's components are (c) IC&S and distributed under the GPL. 
.SH AUTHOR(S)
.na
.nf
Eelco van Beek
IC&S 
Koningsweg 4
3582 GE Utrecht
http://www.ic-s.nl
