.TH DBMAIL-CONFIG 1 
.ad
.fi
.SH NAME
dbmail-config
\-
Changes the internal \fBDbmail\fR mailsystem configuration tables.
.SH SYNOPSIS
.na
.nf
\fBdbmail-config\fR \fI<configfile>\fR
.SH DESCRIPTION
.ad
.fi
\fBDbmail-config\fR will take the configuration options from \fIconfigfile\fR
and update the \fBDbmail\fR config table accordingly.
.SH DIAGNOSTICS
.ad
.fi
Errors and notifications are send to the trace output as configured 
in the \fBDbmail\fR configfile.
.SH BUGS
.PP
Syntax checking needs to be improved.
.SH LICENSE
.na
.nf
.ad
.fi
Dbmail and it's components are (c) IC&S and distributed under the GPL. 
.SH AUTHOR(S)
.na
.nf
Eelco van Beek
IC&S 
Koningsweg 4
3582 GE Utrecht
http://www.ic-s.nl
