.\"     Title: dbmail\-sievecmd
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 08/07/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "DBMAIL\-SIEVECMD" "8" "08/07/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
dbmail\-sievecmd \- manipulates Sieve scripts in the DBMail database.
.SH "SYNOPSIS"
dbmail\-sievecmd \-u username [\-l] [\-a scriptname] [\-d scriptname] [\-i scriptname file] [\-c [scriptname]] [\-e [scriptname]] [\-r scriptname] [\-f configfile] [\-nvVh]
.SH "DESCRIPTION"
DBMail stores Sieve scripts in a table in the DBMail database. These scripts are used to sort incoming mail for the email users. Each user has their own script space and may upload scripts to the dbmail\-timsieved(8) daemon. The dbmail\-sievecmd(8) utility provides a convenient method for the system administrator to work with Sieve scripts from the command line.
.SH "OPTIONS"
.TP 3n
\-u username
Specify the user whose scripts we will be modifying.
.TP 3n
\-l
List scripts belonging to user
.TP 3n
\-a scriptname
Activates
scriptname, deactivating all other scripts.
.TP 3n
\-d scriptname
Deactivates
scriptname
if it was active.
.TP 3n
\-i scriptname file
Creates a script called
scriptname
by importing
file. If
file
is \- (dash) or unspecified,
\fIstdin\fR
will be read.
.TP 3n
\-c [scriptname]
Print out the named script. If no script is given, the active script is printed.
.TP 3n
\-e [scriptname]
Edit the named script. If no script is given, the active script is printed. The EDITOR environment variable is used to find the editor program.
.TP 3n
\-r scriptname
Remove the named script. If the script was active, no script will be active after it is deletion.
.SH "COMMON OPTIONS"
.TP 3n
\-f configfile
Specify an alternate config file. The utilities are currently hardcoded to use /etc/dbmail.conf for their configs, and will halt if the config file cannot be found. Use the \-f configfile option to specify your system's preferred config file location.
.TP 3n
\-q
Quietly skip interactive prompts and helpful status messages which would otherwise be printed to stdout. Use two \-q's to silence errors which would otherwise be printed to stderr.
.TP 3n
\-v
Operate verbosely. Some of the utilities in the DBMail suite can take two \-v's for extra verbosity. Those which don't understand this convention won't complain about having the extra \-v and will simply operate at their normal verbosity.
.TP 3n
\-V
Show the version and copyright, then exit.
.TP 3n
\-h
Show a brief summary of options, then exit.
.SH "BUGS"
If you experience inexplicable problems with DBMail, please report the issue to the [1]\&\fIDBMail Bug Tracker\fR.
.SH "LICENSE"
DBMail and its components are distributed under the terms of the GNU General Public License. Copyrights are held variously by the authors listed below.
.SH "AUTHOR(S)"
DBMail is a collaborative effort among the core developers listed below and the tremendous help of the testers, patchers and bug hunters listed in the AUTHORS and THANKS files found in the DBMail source distribution.
.sp
.RS 3n
.nf
Eelco van Beek      Aaron Stone            Paul J Stevens
Roel Rozendaal      Open Source Engineer   NFG Net Facilities Group BV
Ilja Booij          Palo Alto, CA USA      http://www.nfg.nl
IC&S                http://hydricacid.com
Koningsweg 4
3582 GE Utrecht
http://www.ic\-s.nl
.fi
.sp
.RE
.SH "REFERENCES"
.TP 3
1.\ DBMail Bug Tracker
\%http://dbmail.org/index.php?page=bugs
