'\" t
.\"     Title: dbmail-smtp
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 08/10/2010
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "DBMAIL\-SMTP" "1" "08/10/2010" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
dbmail-smtp \- inserts messages into the DBMail mailsystem\&.
.SH "SYNOPSIS"
.sp
dbmail\-smtp [\-t headerfield] [\-d addresses] [\-u usernames] [\-m|\-M mailboxname] [\-r return path] [\-f configFile]
.SH "DESCRIPTION"
.sp
The dbmail\-smtp program inserts messages from the commandline or from any MTA into the DBMail mailsystem\&. The program reads from standard input\&.
.SH "OPTIONS"
.PP
\-t headerfield
.RS 4
Deliver messages to the recipient MIME header specified in headerfield\&. The default header to use is the "Delivered\-To:" header\&.
.RE
.PP
\-d addresses\&...
.RS 4
Deliver messages to the recipients specified by addresses\&. This option is mostly used for delivery from an MTA\&. Seperate multiple addresses by spaces\&.
.RE
.PP
\-u usernames\&...
.RS 4
Deliver messages straight to the given username\&. Seperate multiple usernames with spaces\&.
.RE
.PP
\-m mailboxname
.RS 4
Deliver messages to mailbox mailboxname of the recipient\&. If this mailbox does not exist yet, it is created\&. Sieve scripts will be run normally, possibly altering the destination mailbox\&.
.RE
.PP
\-M mailboxname
.RS 4
Deliver messages to mailbox mailboxname of the recipient\&. If this mailbox does not exist yet, it is created\&. Sieve scripts are not run\&. Permission checks are not performed for mailbox creation or message delivery\&.
.RE
.PP
\-r returnpath
.RS 4
Set return path for bounces and other error reports to return path\&.
.RE
.SH "COMMON OPTIONS"
.PP
\-f configfile
.RS 4
Specify an alternate config file\&. The utilities are currently hardcoded to use /etc/dbmail\&.conf for their configs, and will halt if the config file cannot be found\&. Use the \-f configfile option to specify your system\(cqs preferred config file location\&.
.RE
.PP
\-q
.RS 4
Quietly skip interactive prompts and helpful status messages which would otherwise be printed to stdout\&. Use two \-q\(cqs to silence errors which would otherwise be printed to stderr\&.
.RE
.PP
\-v
.RS 4
Operate verbosely\&. Some of the utilities in the DBMail suite can take two \-v\(cqs for extra verbosity\&. Those which don\(cqt understand this convention won\(cqt complain about having the extra \-v and will simply operate at their normal verbosity\&.
.RE
.PP
\-V
.RS 4
Show the version and copyright, then exit\&.
.RE
.PP
\-h
.RS 4
Show a brief summary of options, then exit\&.
.RE
.SH "BUGS"
.sp
If you experience inexplicable problems with DBMail, please report the issue to the \m[blue]\fBDBMail Bug Tracker\fR\m[]\&\s-2\u[1]\d\s+2\&.
.SH "LICENSE"
.sp
DBMail and its components are distributed under the terms of the GNU General Public License\&. Copyrights are held variously by the authors listed below\&.
.SH "AUTHOR(S)"
.sp
DBMail is a collaborative effort among the core developers listed below and the tremendous help of the testers, patchers and bug hunters listed in the AUTHORS and THANKS files found in the DBMail source distribution\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Eelco van Beek      Aaron Stone            Paul J Stevens
Roel Rozendaal      Open Source Engineer   NFG Net Facilities Group BV
Ilja Booij          Palo Alto, CA USA      http://www\&.nfg\&.nl
IC&S                http://hydricacid\&.com
Koningsweg 4
3582 GE Utrecht
http://www\&.ic\-s\&.nl
.fi
.if n \{\
.RE
.\}
.SH "NOTES"
.IP " 1." 4
DBMail Bug Tracker
.RS 4
\%http://dbmail.org/index.php?page=bugs
.RE
