# DBMail Dockerfile
# Copyright (c) 2020-2025 Alan Hicks, Persistent Objects Ltd support@p-o.co.uk
# LICENSE GPL2+

FROM debian:bookworm AS build_base
LABEL org.opencontainers.image.authors="ahicks@p-o.co.uk" \
      org.opencontainers.image.url="https://dbmail.org/architecture/docker/" \
      org.opencontainers.image.source="https://github.com/dbmail/dbmail/tree/main/docker" \
      org.opencontainers.image.licenses="GPL-2.0+" \
      org.opencontainers.image.title="DBMail-build-environment" \
      org.opencontainers.image.description="This image contains everything to build dbmail"

RUN apt update && \
    apt install -y \
        make \
        clang-15 \
        git \
        libcurl4-openssl-dev \
        libevent-dev \
        libgmime-3.0-dev \
        libldap2-dev \
        libmhash-dev \
        libssl-dev \
        libsieve2-dev \
        libzdb-dev && \
        update-alternatives --install /usr/bin/cc cc /usr/bin/clang-15 50

FROM build_base AS build
LABEL org.opencontainers.image.authors="ahicks@p-o.co.uk" \
      org.opencontainers.image.url="https://dbmail.org/architecture/docker/" \
      org.opencontainers.image.source="https://github.com/dbmail/dbmail/tree/main/docker" \
      org.opencontainers.image.licenses="GPL-2.0+" \
      org.opencontainers.image.title="DBMail-build" \
      org.opencontainers.image.description="This image builds dbmail"

RUN apt update && \
    apt install -y \
        check \
        libevent-2.1-7 \
        libevent-pthreads-2.1-7 \
        libgmime-3.0-0 \
        libldap-common \
        libmhash2 \
        libsieve2-1 \
        libssl3 \
        libzdb11

RUN mkdir -p /app/dbmail

WORKDIR /app

RUN git clone --branch 3.5.x https://github.com/dbmail/dbmail.git

COPY . dbmail/

RUN cd /app/dbmail && \
    ./configure \
        --with-check \
        --with-ldap=/usr \
        --with-sieve=/usr/lib/x86_64-linux-gnu/ && \
    make && make check && make install

COPY --chown=nobody:nogroup dbmail-imapd.pid /var/run/dbmail/
COPY --chown=nobody:nogroup dbmail-lmtpd.pid /var/run/dbmail/
COPY --chown=nobody:nogroup dbmail-sieved.pid /var/run/dbmail/
COPY --chown=nobody:nogroup dbmail.log /var/log/dbmail/

EXPOSE 143/tcp
EXPOSE 993/tcp
EXPOSE 24/tcp
EXPOSE 4190/tcp

CMD ["/usr/local/sbin/dbmail-imapd", "-D", "-v"]
