# DBMail Dockerfile
# Copyright (c) 2020-2026 Alan Hicks, Persistent Objects Ltd support@p-o.co.uk
# LICENSE GPL2+

FROM debian:bookworm AS build_base
LABEL org.opencontainers.image.authors="ahicks@p-o.co.uk" \
      org.opencontainers.image.url="https://dbmail.org/docs/docker-images/" \
      org.opencontainers.image.source="https://github.com/dbmail/dbmail/tree/master/docker" \
      org.opencontainers.image.licenses="GPL-2.0+" \
      org.opencontainers.image.title="DBMail-build-environment" \
      org.opencontainers.image.description="This image contains everything to build dbmail"

RUN apt update && \
    apt install -y make clang-15 git libgmime-3.0-dev libzdb-dev libldap2-dev \
    libmhash-dev libevent-dev libssl-dev libsieve2-dev libcurl4-openssl-dev && \
    update-alternatives --install /usr/bin/cc cc /usr/bin/clang-15 50
FROM build_base AS build
LABEL org.opencontainers.image.authors="ahicks@p-o.co.uk" \
      org.opencontainers.image.url="https://dbmail.org/docs/docker-images/" \
      org.opencontainers.image.source="https://github.com/dbmail/dbmail/tree/main/docker" \
      org.opencontainers.image.licenses="GPL-2.0+" \
      org.opencontainers.image.title="DBMail-build" \
      org.opencontainers.image.description="This image builds dbmail"

RUN apt update && \
    apt install -y libgmime-3.0-0 libzdb11 libldap-common check \
    libmhash2 libevent-2.1-7 libevent-pthreads-2.1-7 libssl3 libsieve2-1

RUN mkdir -p /app/dbmail

WORKDIR /app
COPY . dbmail/
    #git clone --branch 3.5.x https://github.com/dbmail/dbmail.git && \
RUN cd /app/dbmail && \
    ./configure --with-ldap=/usr --with-sieve=/usr/lib/x86_64-linux-gnu/ --with-check && \
    make && make install
#    make && make check && make install

COPY --chown=nobody:nogroup docker/dbmail-imapd.pid /var/run/dbmail/
COPY --chown=nobody:nogroup docker/dbmail-lmtpd.pid /var/run/dbmail/
COPY --chown=nobody:nogroup docker/dbmail-sieved.pid /var/run/dbmail/
COPY --chown=nobody:nogroup docker/dbmail.log /var/log/dbmail/

CMD ["/usr/local/sbin/dbmail-imapd", "-D", "-v"]
