#!/bin/sh
#
# PROVIDE: dbmail_httpd
# REQUIRE: DAEMON

$_rc_subr_loaded . /etc/rc.subr

name="dbmail_httpd"
rcvar=$name

command="/usr/local/sbin/dbmail-httpd"
command_args=""
pidfile=/var/run/dbmail/dbmail-httpd.pid

load_rc_config $name
run_rc_command "$1"
