#!/bin/sh
#
# PROVIDE: dbmail_pop3d
# REQUIRE: DAEMON

$_rc_subr_loaded . /etc/rc.subr

name="dbmail_pop3d"
rcvar=$name

command="/usr/local/sbin/dbmail-pop3d"
command_args=""
pidfile=/var/run/dbmail/dbmail-pop3d.pid

load_rc_config $name
run_rc_command "$1"
