#!/bin/sh
#
# PROVIDE: dbmail_sieved
# REQUIRE: DAEMON

$_rc_subr_loaded . /etc/rc.subr

name="dbmail_sieved"
rcvar=$name

command="/usr/local/sbin/dbmail-sieved"
command_args=""
pidfile=/var/run/dbmail/dbmail-sieved.pid

load_rc_config $name
run_rc_command "$1"
