#!/bin/sh
#
# PROVIDE: dbmail_imapd
# REQUIRE: DAEMON

$_rc_subr_loaded . /etc/rc.subr

name="dbmail_imapd"
rcvar=$name

command="/usr/local/sbin/dbmail-imapd"
command_args=""
pidfile=/var/run/dbmail/dbmail-imapd.pid

load_rc_config $name
run_rc_command "$1"
